org: rolandodiaz
service: api-compras

provider:
  name: aws
  runtime: python3.11
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::409362080365:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_compras
    JWT_SECRET: mi-super-secreto-jwt-2025

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false

functions:
  registrar-compra:
    handler: compras.registrar_compra
    events:
      - http:
          path: /compras/registrar
          method: post
          cors: true
          integration: lambda
  
  listar-compras:
    handler: compras.listar_compras
    events:
      - http:
          path: /compras/listar
          method: get
          cors: true
          integration: lambda
  
  buscar-compra:
    handler: compras.buscar_compra
    events:
      - http:
          path: /compras/buscar/{codigo}
          method: get
          cors: true
          integration: lambda
  
  estadisticas-compras:
    handler: compras.obtener_estadisticas_compras
    events:
      - http:
          path: /compras/estadisticas
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaCompras:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: codigo_compra
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: codigo_compra
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

plugins:
  - serverless-python-requirements